# This file was generated by GoReleaser. DO NOT EDIT.
cask "beeper-cli" do
  name "beeper-cli"
  desc "CLI for interacting with Beeper Desktop's local API"
  homepage "https://github.com/salmonumbrella/beeper-cli"
  version "0.2.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beeper"

  on_macos do
    on_intel do
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v#{version}/beeper-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "610a2b1e4f509027b8eacec5261161850444a3cd6af6980f8a8d0cd4d4fe98f2"
    end
    on_arm do
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v#{version}/beeper-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "22e9ee5f8317678b3e4d59da9df6abddcfb5c6bdc1003fc62016a33c5ce0fcac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v#{version}/beeper-cli_#{version}_linux_amd64.tar.gz"
      sha256 "7c6ff4abe50220021b8aa108eea4a26766ce26e3b700eef9b89c635ecac733e5"
    end
    on_arm do
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v#{version}/beeper-cli_#{version}_linux_arm64.tar.gz"
      sha256 "032fa89968438a7470f5e98cd797e1b92f554ce15bccc6af60946b642fbc9c25"
    end
  end

  # No zap stanza required
end
