# This file was generated by GoReleaser. DO NOT EDIT.
cask "line-official-cli" do
  name "line-official-cli"
  desc "CLI for LINE Official Account / Messaging API"
  homepage "https://github.com/salmonumbrella/line-official-cli"
  version "0.3.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "line-official"
  binary "line"

  on_macos do
    on_intel do
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v#{version}/line-official-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "8cb54e07a40dd056e7c6a0fcad4ef0daaa2c33245973cb9c36d81ad268e178d7"
    end
    on_arm do
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v#{version}/line-official-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "b6bee6a23bd8f5b4cfc40328a7f8ed225ea58d2ca4a2341edf2f1cb83c7b6455"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v#{version}/line-official-cli_#{version}_linux_amd64.tar.gz"
      sha256 "50cd5e41d544ec416dec0971f17eeffae18bfc80b20d515c6a66767ce720db26"
    end
    on_arm do
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v#{version}/line-official-cli_#{version}_linux_arm64.tar.gz"
      sha256 "a5a1fb287efcf5a3fc0d6e8c9a626957069cb443cb779131a1eeb4edd39f0162"
    end
  end

  # No zap stanza required
end
