# This file was generated by GoReleaser. DO NOT EDIT.
cask "line-official-cli" do
  name "line-official-cli"
  desc "CLI for LINE Official Account / Messaging API"
  homepage "https://github.com/salmonumbrella/line-official-cli"
  version "0.3.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "line-official"

  on_macos do
    on_intel do
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v#{version}/line-official-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "8814392eabe604f8a9a0d8def404beb0b7e1b853686744b27fc730423106c713"
    end
    on_arm do
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v#{version}/line-official-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "67f6af3e26a0a8029e71430aab3617d6b4d765191ee1e661daa631dabc4eccc2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v#{version}/line-official-cli_#{version}_linux_amd64.tar.gz"
      sha256 "2b1681d033c9073feff1a52314176219ed82abe7060d2f926c051ff236defe57"
    end
    on_arm do
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v#{version}/line-official-cli_#{version}_linux_arm64.tar.gz"
      sha256 "32fce59d255fa8d37fd0bda2337799ded4e757a414dd61fb0de9d1901f9f3cac"
    end
  end

  # No zap stanza required
end
