# This file was generated by GoReleaser. DO NOT EDIT.
cask "notion-cli" do
  name "notion-cli"
  desc "CLI for Notion API"
  homepage "https://github.com/salmonumbrella/notion-cli"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notion-cli"

  on_macos do
    on_intel do
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v#{version}/notion_darwin_amd64.tar.gz"
      sha256 "fcb5760a2d7049f49eefc970fa5805f1f79ef6b2f53e00c0e81d24d0ffb2cef0"
    end
    on_arm do
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v#{version}/notion_darwin_arm64.tar.gz"
      sha256 "a30a55e98eb870655c9f27502ff72a8adecb8ce2bd0c21b121b5a20fcd3a9e88"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v#{version}/notion_linux_amd64.tar.gz"
      sha256 "a973ba25cd2a7882c65b59c73bd021f698d2e29d71ba326a2d876adc6f9627f9"
    end
    on_arm do
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v#{version}/notion_linux_arm64.tar.gz"
      sha256 "4f5e6eb572221fa8abd350a63efe7193928a6aed625b2def6b2cc96fbbba011f"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}/notion"]
  end

  # No zap stanza required
end
