# This file was generated by GoReleaser. DO NOT EDIT.
cask "notion-cli" do
  name "notion-cli"
  desc "CLI for Notion API"
  homepage "https://github.com/salmonumbrella/notion-cli"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notion-cli"

  on_macos do
    on_intel do
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v#{version}/notion_darwin_amd64.tar.gz"
      sha256 "d3023043fcb4480fcdf05a263e06f4ee41ca09952462c3c29c203e2aab418b45"
    end
    on_arm do
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v#{version}/notion_darwin_arm64.tar.gz"
      sha256 "821e725ba763ba5d5f758d76feeebdf0ee76fe602e0a992040e50753f67f466c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v#{version}/notion_linux_amd64.tar.gz"
      sha256 "1b7a0dcedd4795c09653af14f40660909d0fad618aed28e281daaff5599a0bf4"
    end
    on_arm do
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v#{version}/notion_linux_arm64.tar.gz"
      sha256 "62b97fa56d0f02cb16ecd54179234588cb300f8a1a425107500bd3f92107fcfc"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}/notion"]
  end

  # No zap stanza required
end
