# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AirwallexCli < Formula
  desc "CLI for Airwallex to manage transfers, beneficiaries, and balances"
  homepage "https://github.com/salmonumbrella/airwallex-cli"
  version "0.2.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/airwallex-cli/releases/download/v0.2.16/airwallex-cli_0.2.16_darwin_amd64.tar.gz"
      sha256 "1febc3787d6b03cb37acd03cb5ad9fb289dff217f037cc718f471b02c0930660"

      def install
        bin.install "airwallex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/airwallex-cli/releases/download/v0.2.16/airwallex-cli_0.2.16_darwin_arm64.tar.gz"
      sha256 "3ff1dc76d5706ce34260df84720dab41a06bde0166f5a9e9617dacbad2e82947"

      def install
        bin.install "airwallex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/airwallex-cli/releases/download/v0.2.16/airwallex-cli_0.2.16_linux_amd64.tar.gz"
      sha256 "36b3567173e84a3125320bbae3d698cabfa50167bcf8a6e7422c442a9acc4af5"
      def install
        bin.install "airwallex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/airwallex-cli/releases/download/v0.2.16/airwallex-cli_0.2.16_linux_arm64.tar.gz"
      sha256 "bcb51b1322f9fc2cc60cf5f54e83d8e02692701c4258862dbde5c7f493258fd0"
      def install
        bin.install "airwallex"
      end
    end
  end

  test do
    system "#{bin}/airwallex", "--help"
  end
end
