# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AirwallexCli < Formula
  desc "CLI for Airwallex to manage transfers, beneficiaries, and balances"
  homepage "https://github.com/salmonumbrella/airwallex-cli"
  version "0.2.29"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/airwallex-cli/releases/download/v0.2.29/airwallex-cli_0.2.29_darwin_amd64.tar.gz"
      sha256 "ebcc6dcf3a21305a808d58ef0918034f71a4802671908f74dd10603665e96552"

      define_method(:install) do
        bin.install "awx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/airwallex-cli/releases/download/v0.2.29/airwallex-cli_0.2.29_darwin_arm64.tar.gz"
      sha256 "972471354510056c5808e663c418dbbc1c1bd2d969732e8f1309976274ebb603"

      define_method(:install) do
        bin.install "awx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/airwallex-cli/releases/download/v0.2.29/airwallex-cli_0.2.29_linux_amd64.tar.gz"
      sha256 "9bbf71a79b665a79895e93022ee8ddc623604b489508db0707a89ebea35cf62e"
      define_method(:install) do
        bin.install "awx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/airwallex-cli/releases/download/v0.2.29/airwallex-cli_0.2.29_linux_arm64.tar.gz"
      sha256 "d47d13800c540a47aecdf49c03572f877c3c522d02138b14c276ab0cc3669455"
      define_method(:install) do
        bin.install "awx"
      end
    end
  end

  test do
    system "#{bin}/awx", "--help"
  end
end
