# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AirwallexCli < Formula
  desc "CLI for Airwallex to manage transfers, beneficiaries, and balances"
  homepage "https://github.com/salmonumbrella/airwallex-cli"
  version "0.2.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/airwallex-cli/releases/download/v0.2.10/airwallex-cli_0.2.10_darwin_amd64.tar.gz"
      sha256 "8d4fdbe565e3c7bb901c943a2dda53371d7e60af7f89594d9b320170fb2ad1db"

      def install
        bin.install "airwallex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/airwallex-cli/releases/download/v0.2.10/airwallex-cli_0.2.10_darwin_arm64.tar.gz"
      sha256 "972c09c08f82f4fb0c4744d937aaf3261f6379823ae1618d3422cec8cd5ec8f0"

      def install
        bin.install "airwallex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/airwallex-cli/releases/download/v0.2.10/airwallex-cli_0.2.10_linux_amd64.tar.gz"
      sha256 "8f0c9cc6f6baa2c1e1c28540d2cc6b9fc682749b9c6ceaf41b081db14a8e5f7d"
      def install
        bin.install "airwallex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/airwallex-cli/releases/download/v0.2.10/airwallex-cli_0.2.10_linux_arm64.tar.gz"
      sha256 "b07fc6223a555e8fb29ad8729d543834c619ba9199e0ef25da007f26bd497da9"
      def install
        bin.install "airwallex"
      end
    end
  end

  test do
    system "#{bin}/airwallex", "--help"
  end
end
