# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BeeperCli < Formula
  desc "CLI for interacting with Beeper Desktop's local API"
  homepage "https://github.com/salmonumbrella/beeper-cli"
  version "0.2.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v0.2.11/beeper-cli_0.2.11_darwin_amd64.tar.gz"
      sha256 "fa6b280eb9e66d756822604cbc957d6bc61a77bb33ff86d328cb287317565f2b"

      def install
        bin.install "beeper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v0.2.11/beeper-cli_0.2.11_darwin_arm64.tar.gz"
      sha256 "d304cf94710c8f844d03a27ddddb5af2d743b096a1b24ec416a8cea3b8c35b52"

      def install
        bin.install "beeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v0.2.11/beeper-cli_0.2.11_linux_amd64.tar.gz"
      sha256 "43cb97dd36f6cb7e0aa35e794c67ce86245a8b50b3fe349ce06738de99ef1349"
      def install
        bin.install "beeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v0.2.11/beeper-cli_0.2.11_linux_arm64.tar.gz"
      sha256 "22ca5d2e54ce8b3ba3c214974d0551176bf604b5a1dacee8d0082fcfde694dca"
      def install
        bin.install "beeper"
      end
    end
  end

  test do
    system "#{bin}/beeper", "--help"
  end
end
