# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BeeperCli < Formula
  desc "CLI for interacting with Beeper Desktop's local API"
  homepage "https://github.com/salmonumbrella/beeper-cli"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v0.1.4/beeper-cli_0.1.4_darwin_amd64.tar.gz"
      sha256 "349eeb3e4890b72971fc771b8998276fa0d2d51c89c76e053f6d7fdd228ccb50"

      def install
        bin.install "beeper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v0.1.4/beeper-cli_0.1.4_darwin_arm64.tar.gz"
      sha256 "9e94810d28750b6802fd38ff22a2641ff9119fc3bb47e60ffafb184c538b217a"

      def install
        bin.install "beeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v0.1.4/beeper-cli_0.1.4_linux_amd64.tar.gz"
      sha256 "aecef4504be30c8b637b46a7b9a04993285575725bbd36853e45d4ac214307ad"
      def install
        bin.install "beeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v0.1.4/beeper-cli_0.1.4_linux_arm64.tar.gz"
      sha256 "0fc2f7a3d766e580ebaca947e7e82e9c21b8d690a1ceb900c01e6fff5f9be135"
      def install
        bin.install "beeper"
      end
    end
  end

  test do
    system "#{bin}/beeper", "--help"
  end
end
