# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BeeperCli < Formula
  desc "CLI for interacting with Beeper Desktop's local API"
  homepage "https://github.com/salmonumbrella/beeper-cli"
  version "0.2.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v0.2.17/beeper-cli_0.2.17_darwin_amd64.tar.gz"
      sha256 "91298381a86a389dae22b14cc4ed471d81278ee3a4c909ed4b6ee5a986d85158"

      define_method(:install) do
        bin.install "beeper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v0.2.17/beeper-cli_0.2.17_darwin_arm64.tar.gz"
      sha256 "31fcf9035361568efa342b8cce462715f3596b4f31cde2749500e88c9ae24885"

      define_method(:install) do
        bin.install "beeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v0.2.17/beeper-cli_0.2.17_linux_amd64.tar.gz"
      sha256 "527f1a42d3933a319e17005f2ecc52120d29f1e0dfae87bd4f281113c1e035f8"
      define_method(:install) do
        bin.install "beeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/beeper-cli/releases/download/v0.2.17/beeper-cli_0.2.17_linux_arm64.tar.gz"
      sha256 "d9746552e4c7ee67ca82b7399167a3d77d4131dfea5c92c10025333f44e436b0"
      define_method(:install) do
        bin.install "beeper"
      end
    end
  end

  test do
    system "#{bin}/beeper", "--help"
  end
end
