# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bgo < Formula
  desc "BigGo price comparison CLI - search products, track prices, and analyze deals"
  homepage "https://github.com/salmonumbrella/bgo"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/bgo/releases/download/v0.1.0/bgo_0.1.0_darwin_amd64.tar.gz"
      sha256 "e3978d6cb7d9f50b451031840347206ea66f77e240d92cf8e9d3375575072c72"

      def install
        bin.install "bgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/bgo/releases/download/v0.1.0/bgo_0.1.0_darwin_arm64.tar.gz"
      sha256 "b67300ddd78b34100c4873f90624fe8f5a1b25c12aad3e81f7d1498449355fb4"

      def install
        bin.install "bgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/bgo/releases/download/v0.1.0/bgo_0.1.0_linux_amd64.tar.gz"
      sha256 "68f36b27596bc3e3db6d1174c8f6f5a84909693a66a110fd7ec7b5d3176b2397"
      def install
        bin.install "bgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/bgo/releases/download/v0.1.0/bgo_0.1.0_linux_arm64.tar.gz"
      sha256 "3d5526856b67bf70554dc55b3e82e55e118e21f581c74d149a4e695402883af9"
      def install
        bin.install "bgo"
      end
    end
  end

  test do
    system "#{bin}/bgo", "version"
  end
end
