# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bgo < Formula
  desc "BigGo price comparison CLI - search products, track prices, and analyze deals"
  homepage "https://github.com/salmonumbrella/biggo-cli"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/biggo-cli/releases/download/v0.1.5/bgo_0.1.5_darwin_amd64.tar.gz"
      sha256 "13e9c07d216a5bbb0e95619898c10fc87a91ae5e044d05aa297df1a295572fa7"

      define_method(:install) do
        bin.install "bgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/biggo-cli/releases/download/v0.1.5/bgo_0.1.5_darwin_arm64.tar.gz"
      sha256 "c3e5f231e3b7fd012499244733b2323bb54976f299834ba217bac40e1d8fb3ff"

      define_method(:install) do
        bin.install "bgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/biggo-cli/releases/download/v0.1.5/bgo_0.1.5_linux_amd64.tar.gz"
      sha256 "14ddae19bf062a5dd71a0b4b6ccc30b77cd0557450b3e1b63b9bf0e422f0f515"
      define_method(:install) do
        bin.install "bgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/biggo-cli/releases/download/v0.1.5/bgo_0.1.5_linux_arm64.tar.gz"
      sha256 "4a8dcc2bc08da52191dc6207ca212dad37a4f8c60b56095ef07ab832bd58946a"
      define_method(:install) do
        bin.install "bgo"
      end
    end
  end

  test do
    system "#{bin}/bgo", "version"
  end
end
