# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bgo < Formula
  desc "BigGo price comparison CLI - search products, track prices, and analyze deals"
  homepage "https://github.com/salmonumbrella/biggo-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/biggo-cli/releases/download/v0.1.2/bgo_0.1.2_darwin_amd64.tar.gz"
      sha256 "2869012b839297fa4f60b1c040fa659fbbd622a6c11100e8e7abcb3ac4c10981"

      define_method(:install) do
        bin.install "bgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/biggo-cli/releases/download/v0.1.2/bgo_0.1.2_darwin_arm64.tar.gz"
      sha256 "49f2e9104546113eb553a978795a9f4ad2accdf015c961a16a563b155494fca8"

      define_method(:install) do
        bin.install "bgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/biggo-cli/releases/download/v0.1.2/bgo_0.1.2_linux_amd64.tar.gz"
      sha256 "1261a9629ae063524c87935f7b969ed2befb3d48aa773270b1e7b43e770d7a13"
      define_method(:install) do
        bin.install "bgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/biggo-cli/releases/download/v0.1.2/bgo_0.1.2_linux_arm64.tar.gz"
      sha256 "c660df03c054a0efb0c3bfa06353a55a080d9fd232a9aca75f7cd99382e4ff24"
      define_method(:install) do
        bin.install "bgo"
      end
    end
  end

  test do
    system "#{bin}/bgo", "version"
  end
end
