# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BiggoCli < Formula
  desc "BigGo price comparison CLI - search products, track prices, and analyze deals"
  homepage "https://github.com/salmonumbrella/biggo-cli"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/biggo-cli/releases/download/v0.1.4/bgo_0.1.4_darwin_amd64.tar.gz"
      sha256 "c6c2ad446dc475f587d114e60e4b11fee7a73fbd7671c8fbfbb2883188e6017a"

      define_method(:install) do
        bin.install "bgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/biggo-cli/releases/download/v0.1.4/bgo_0.1.4_darwin_arm64.tar.gz"
      sha256 "cbb1c91f9cb8b4628c4abc55b7ebaaba1415eb625f0c60d8ca7ebf8a16d57380"

      define_method(:install) do
        bin.install "bgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/biggo-cli/releases/download/v0.1.4/bgo_0.1.4_linux_amd64.tar.gz"
      sha256 "6d49476da442925e498d1e85848cb1f798c32793b2b4d358d3463db32532ee48"
      define_method(:install) do
        bin.install "bgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/biggo-cli/releases/download/v0.1.4/bgo_0.1.4_linux_arm64.tar.gz"
      sha256 "9ecd4bcf7370364e880ed770742e95ca46eaedf2b604d98775a13f1bf3bd1c79"
      define_method(:install) do
        bin.install "bgo"
      end
    end
  end

  test do
    system "#{bin}/bgo", "version"
  end
end
