# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrandfetchCli < Formula
  desc "CLI for Brandfetch to fetch logos, colors, and brand assets"
  homepage "https://github.com/salmonumbrella/brandfetch-cli"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/brandfetch-cli/releases/download/v0.1.5/brandfetch_0.1.5_darwin_amd64.tar.gz"
      sha256 "4546ca21a418b9b6ab6975309a6ac7101e73b3ae6d71cf958e0e45daf74c2d7d"

      define_method(:install) do
        bin.install "brandfetch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/brandfetch-cli/releases/download/v0.1.5/brandfetch_0.1.5_darwin_arm64.tar.gz"
      sha256 "0f987295cecc5d005bd24d016614b12bb84324d2c6ab9b00d8b756779c1c1c4b"

      define_method(:install) do
        bin.install "brandfetch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/brandfetch-cli/releases/download/v0.1.5/brandfetch_0.1.5_linux_amd64.tar.gz"
      sha256 "2c9cf93ce3dddfa1d0fee580a3c6e28b989712cf43337de2f34b09058c970507"
      define_method(:install) do
        bin.install "brandfetch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/brandfetch-cli/releases/download/v0.1.5/brandfetch_0.1.5_linux_arm64.tar.gz"
      sha256 "33980253264eddaf9c513e2ca03228e108f241558ee2ee4e7c772c2c95df0cb1"
      define_method(:install) do
        bin.install "brandfetch"
      end
    end
  end

  test do
    system "#{bin}/brandfetch", "--help"
  end
end
