# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatwootCli < Formula
  desc "CLI for Chatwoot to manage conversations, contacts, and inboxes"
  homepage "https://github.com/salmonumbrella/chatwoot-cli"
  version "0.2.27"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/chatwoot-cli/releases/download/v0.2.27/chatwoot-cli_0.2.27_darwin_amd64.tar.gz"
      sha256 "a49b356b994fdf19b81a857a423bed2209954659041d918ff72dca1994894b43"

      def install
        bin.install "cw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/chatwoot-cli/releases/download/v0.2.27/chatwoot-cli_0.2.27_darwin_arm64.tar.gz"
      sha256 "04b6ffafef575b71c6f2d9425f5303db0196baac04cc86f1c48a99bd110ac80d"

      def install
        bin.install "cw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/chatwoot-cli/releases/download/v0.2.27/chatwoot-cli_0.2.27_linux_amd64.tar.gz"
      sha256 "cec1a528b378c2ca251836cfb95b191b656ae6edc4b206a2eacab1b40f7f636c"
      def install
        bin.install "cw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/chatwoot-cli/releases/download/v0.2.27/chatwoot-cli_0.2.27_linux_arm64.tar.gz"
      sha256 "bd88afdf010211d527e363a32f57cbc7fd34896cdf25fe1be77db0ba5ba0ed33"
      def install
        bin.install "cw"
      end
    end
  end

  test do
    system "#{bin}/cw", "--help"
  end
end
