# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatwootCli < Formula
  desc "CLI for Chatwoot to manage conversations, contacts, and inboxes"
  homepage "https://github.com/salmonumbrella/chatwoot-cli"
  version "0.2.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/chatwoot-cli/releases/download/v0.2.11/chatwoot-cli_0.2.11_darwin_amd64.tar.gz"
      sha256 "b2286c7272562ea42d44323d184ab9012475afe99aad7028dc61994b8cf7ff0c"

      def install
        bin.install "chatwoot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/chatwoot-cli/releases/download/v0.2.11/chatwoot-cli_0.2.11_darwin_arm64.tar.gz"
      sha256 "38cabec45488f65b95c4d9c69f9f94ed73db6b2f251e3438cf4850b3aa67f5b0"

      def install
        bin.install "chatwoot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/chatwoot-cli/releases/download/v0.2.11/chatwoot-cli_0.2.11_linux_amd64.tar.gz"
      sha256 "89f6dd1b55b8cd7d27ab6fc5b1b9df666ee6a3b533dce4e819167d994ce09fa7"
      def install
        bin.install "chatwoot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/chatwoot-cli/releases/download/v0.2.11/chatwoot-cli_0.2.11_linux_arm64.tar.gz"
      sha256 "d068060de8797a5d9b2aafaaeba23a9e62493a760b6683a01d2fa4c071afe737"
      def install
        bin.install "chatwoot"
      end
    end
  end

  test do
    system "#{bin}/chatwoot", "--help"
  end
end
