# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ControldCli < Formula
  desc "CLI for ControlD DNS management - manage devices, profiles, and DNS filtering"
  homepage "https://github.com/salmonumbrella/controld-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/controld-cli/releases/download/v0.1.0/controld-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "4eb3a8ef38d5bb9c9b2b6b55769489b21a20e503ac52ca4279d74e2924a09962"

      def install
        bin.install "controld"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/controld-cli/releases/download/v0.1.0/controld-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "e74f9c9c93ad741aa954cb85a573c5fce0d5de49a6c097014693d9344e4232e5"

      def install
        bin.install "controld"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/controld-cli/releases/download/v0.1.0/controld-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "bfdf3818e32e2074f6db71a50919cacaed47378c0298f24a047f8b6309719142"
      def install
        bin.install "controld"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/controld-cli/releases/download/v0.1.0/controld-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "c901ae2ec313137cdf4038d9d948341ed0590eb1d58d4f17459f1b8cb35fc96f"
      def install
        bin.install "controld"
      end
    end
  end

  test do
    system "#{bin}/controld", "--help"
  end
end
