# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ControldCli < Formula
  desc "CLI for ControlD DNS management - manage devices, profiles, and DNS filtering"
  homepage "https://github.com/salmonumbrella/controld-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/controld-cli/releases/download/v0.1.3/controld-cli_0.1.3_darwin_amd64.tar.gz"
      sha256 "bf0f56bab41e0b281a5c32b52cd1da425ba0d9a5b389a6b896fa05d8cd3c20a5"

      define_method(:install) do
        bin.install "controld"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/controld-cli/releases/download/v0.1.3/controld-cli_0.1.3_darwin_arm64.tar.gz"
      sha256 "45b514de6a6dc2a4e3f37078ff3e992f75af447e8585c3c9e8611d2645a3d642"

      define_method(:install) do
        bin.install "controld"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/controld-cli/releases/download/v0.1.3/controld-cli_0.1.3_linux_amd64.tar.gz"
      sha256 "2f77ec57063ad79a154f05184a30151694faf62a176392a1c60f59bba9ca1f35"
      define_method(:install) do
        bin.install "controld"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/controld-cli/releases/download/v0.1.3/controld-cli_0.1.3_linux_arm64.tar.gz"
      sha256 "419693d254946cd7ce5350aa003254df7793c4dc179ec89dba1886182833fce9"
      define_method(:install) do
        bin.install "controld"
      end
    end
  end

  test do
    system "#{bin}/controld", "--help"
  end
end
