# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeputyCli < Formula
  desc "CLI for Deputy to manage employees, timesheets, rosters, and leave"
  homepage "https://github.com/salmonumbrella/deputy-cli"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/deputy-cli/releases/download/v0.1.12/deputy-cli_0.1.12_darwin_amd64.tar.gz"
      sha256 "7c3eb5d06ccbe48bd963d3b8604ce04fe23d59569de3c25d1cf45015d5b25a2a"

      define_method(:install) do
        bin.install "deputy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/deputy-cli/releases/download/v0.1.12/deputy-cli_0.1.12_darwin_arm64.tar.gz"
      sha256 "2b3f789480a9cb3d61e737835cbda7bc9b5c81c67d4085871cee8317705a7bb1"

      define_method(:install) do
        bin.install "deputy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/deputy-cli/releases/download/v0.1.12/deputy-cli_0.1.12_linux_amd64.tar.gz"
      sha256 "a852fbd06cb665e41a3045b0a3ceaaaed2ba18c09dde3ebd615fb69a35be9625"
      define_method(:install) do
        bin.install "deputy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/deputy-cli/releases/download/v0.1.12/deputy-cli_0.1.12_linux_arm64.tar.gz"
      sha256 "19645b6ff7a0e82f6d141ca10a0196106dbc4ec01cf2f13503241ebc043ed04e"
      define_method(:install) do
        bin.install "deputy"
      end
    end
  end

  test do
    system "#{bin}/deputy", "--help"
  end
end
