# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeputyCli < Formula
  desc "CLI for Deputy to manage employees, timesheets, rosters, and leave"
  homepage "https://github.com/salmonumbrella/deputy-cli"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/deputy-cli/releases/download/v0.1.11/deputy-cli_0.1.11_darwin_amd64.tar.gz"
      sha256 "bef991afba8179625b59c6df3a7590fa6a3e606e5ea290df8b26bf0cf156aac2"

      def install
        bin.install "deputy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/deputy-cli/releases/download/v0.1.11/deputy-cli_0.1.11_darwin_arm64.tar.gz"
      sha256 "b182dc95ea72100af934d505086aa2a839bf1fa0f285345d5e76296dcdac50d1"

      def install
        bin.install "deputy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/deputy-cli/releases/download/v0.1.11/deputy-cli_0.1.11_linux_amd64.tar.gz"
      sha256 "3097bf5d5fd726a41c71b875ba4b86025d6e4efe4e4e6bff88c7415ff8d8fe09"
      def install
        bin.install "deputy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/deputy-cli/releases/download/v0.1.11/deputy-cli_0.1.11_linux_arm64.tar.gz"
      sha256 "6ca327cebe6afa8562df24f8604831aa495769baa5e4976a4e6b0bb8584a5aaa"
      def install
        bin.install "deputy"
      end
    end
  end

  test do
    system "#{bin}/deputy", "--help"
  end
end
