# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DocusealCli < Formula
  desc "CLI for DocuSeal to manage documents, submissions, and templates"
  homepage "https://github.com/salmonumbrella/docuseal-cli"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/docuseal-cli/releases/download/v0.2.4/docuseal_0.2.4_darwin_amd64.tar.gz"
      sha256 "56dc82b31d3830a7b84142b56d78be5c6dc61fc4b91ee9890480d7c571d338c6"

      define_method(:install) do
        bin.install "docuseal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/docuseal-cli/releases/download/v0.2.4/docuseal_0.2.4_darwin_arm64.tar.gz"
      sha256 "a32912fea25da6445ef8b615d180bcb6e826b4cb77cb29cdb5646b9357a77c5a"

      define_method(:install) do
        bin.install "docuseal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/docuseal-cli/releases/download/v0.2.4/docuseal_0.2.4_linux_amd64.tar.gz"
      sha256 "02e12726691b9c221f6739ee53b0d75dff533f4598c217922c54cf595fbdaef2"
      define_method(:install) do
        bin.install "docuseal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/docuseal-cli/releases/download/v0.2.4/docuseal_0.2.4_linux_arm64.tar.gz"
      sha256 "dc4cae6d20e9bd8ea8531987b1c96c8f01791f857677551c8f58faecc1574d4e"
      define_method(:install) do
        bin.install "docuseal"
      end
    end
  end

  test do
    system "#{bin}/docuseal", "--help"
  end
end
