# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DubCli < Formula
  desc "CLI for Dub.co to manage links, domains, analytics, and workspaces"
  homepage "https://github.com/salmonumbrella/dub-cli"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/dub-cli/releases/download/v0.1.5/dub-cli_0.1.5_darwin_amd64.tar.gz"
      sha256 "a615a5eca5b4c5475ec33b22da12a3e01a4a80445d0f7c05d09c433bec04e056"

      define_method(:install) do
        bin.install "dub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/dub-cli/releases/download/v0.1.5/dub-cli_0.1.5_darwin_arm64.tar.gz"
      sha256 "f74e41a5bdceefde1c5eadb272bbec86aad86bef97442b25b9a8e33b2e96cc07"

      define_method(:install) do
        bin.install "dub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/dub-cli/releases/download/v0.1.5/dub-cli_0.1.5_linux_amd64.tar.gz"
      sha256 "60a46e84e793c64406f441bebfc96a0884a04d8e8743655a8249f2a5f8f4416c"
      define_method(:install) do
        bin.install "dub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/dub-cli/releases/download/v0.1.5/dub-cli_0.1.5_linux_arm64.tar.gz"
      sha256 "aaca8445cc1f62d13962baa28b3272c94460f5f4436b98ca89f232fe1dda3f4b"
      define_method(:install) do
        bin.install "dub"
      end
    end
  end

  test do
    system "#{bin}/dub", "--help"
  end
end
