# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EightsleepCli < Formula
  desc "CLI for Eight Sleep to control temperature, alarms, and sleep metrics"
  homepage "https://github.com/salmonumbrella/eightsleep-cli"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/eightsleep-cli/releases/download/v0.2.7/eightsleep-cli_0.2.7_darwin_amd64.tar.gz"
      sha256 "0692194751e946100ef4d564c48f820e837c25bea8b6313f43381a0f305ff970"

      def install
        bin.install "eightsleep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/eightsleep-cli/releases/download/v0.2.7/eightsleep-cli_0.2.7_darwin_arm64.tar.gz"
      sha256 "823f02a8daf11d092e62172eee399f76cb2305606477640eb0ec74f7acc81d87"

      def install
        bin.install "eightsleep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/eightsleep-cli/releases/download/v0.2.7/eightsleep-cli_0.2.7_linux_amd64.tar.gz"
      sha256 "c7a59342f413bc9fd1636304fdf075926e07918f2eb48bda3dfd7f8b57a6d08f"
      def install
        bin.install "eightsleep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/eightsleep-cli/releases/download/v0.2.7/eightsleep-cli_0.2.7_linux_arm64.tar.gz"
      sha256 "ffeb2cf708f681d5ba88f7284d60785cb5997479903e0f1e3e29a58ed8a1a0ef"
      def install
        bin.install "eightsleep"
      end
    end
  end

  test do
    system "#{bin}/eightsleep", "--help"
  end
end
