# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EightsleepCli < Formula
  desc "CLI for Eight Sleep to control temperature, alarms, and sleep metrics"
  homepage "https://github.com/salmonumbrella/eightsleep-cli"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/eightsleep-cli/releases/download/v0.2.6/eightsleep-cli_0.2.6_darwin_amd64.tar.gz"
      sha256 "c506ed28e3a0d7768fe2c17c39973ba9299c3f320cee0bd767bdc95474ac1ee2"

      def install
        bin.install "eightsleep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/eightsleep-cli/releases/download/v0.2.6/eightsleep-cli_0.2.6_darwin_arm64.tar.gz"
      sha256 "36906d2fabe07d54007dc164443371f0b1c237bb6e93f7e6e57fe65608ff58ef"

      def install
        bin.install "eightsleep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/eightsleep-cli/releases/download/v0.2.6/eightsleep-cli_0.2.6_linux_amd64.tar.gz"
      sha256 "72037a440c380e8815d9c150f18ccf9127295b8d5fac673375b0e86c5d51dbcf"
      def install
        bin.install "eightsleep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/eightsleep-cli/releases/download/v0.2.6/eightsleep-cli_0.2.6_linux_arm64.tar.gz"
      sha256 "7686ecfd5830d2be51da45b7e09d021c590a1d3771cabc05eb788490ea7d78d8"
      def install
        bin.install "eightsleep"
      end
    end
  end

  test do
    system "#{bin}/eightsleep", "--help"
  end
end
