# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EightsleepCli < Formula
  desc "CLI for Eight Sleep to control temperature, alarms, and sleep metrics"
  homepage "https://github.com/salmonumbrella/eightsleep-cli"
  version "0.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/eightsleep-cli/releases/download/v0.2.8/eightsleep-cli_0.2.8_darwin_amd64.tar.gz"
      sha256 "74fa778aa040610c08f7baeb2bcd028df2d558a22a032501820ce496d092b0af"

      define_method(:install) do
        bin.install "eightsleep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/eightsleep-cli/releases/download/v0.2.8/eightsleep-cli_0.2.8_darwin_arm64.tar.gz"
      sha256 "dde38fae05a49b1ebb27ef16e5fae38ce4b3b5f7684bc030dc24f592c7895815"

      define_method(:install) do
        bin.install "eightsleep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/eightsleep-cli/releases/download/v0.2.8/eightsleep-cli_0.2.8_linux_amd64.tar.gz"
      sha256 "88fa4dad26bdfd4ddfa5faeeee0bfa186be88ae5f9eb194fbacc3b9dab1fa868"
      define_method(:install) do
        bin.install "eightsleep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/eightsleep-cli/releases/download/v0.2.8/eightsleep-cli_0.2.8_linux_arm64.tar.gz"
      sha256 "f0778d4d0ec924d231c2dea0a0d63b3fbcc83ce89fb1f2dc1f26e70d716bf8c3"
      define_method(:install) do
        bin.install "eightsleep"
      end
    end
  end

  test do
    system "#{bin}/eightsleep", "--help"
  end
end
