# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FacebookCli < Formula
  desc "CLI for Facebook Graph API to manage pages, posts, ads, and analytics"
  homepage "https://github.com/salmonumbrella/facebook-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/facebook-cli/releases/download/v0.1.0/facebook-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "e7c8cf829985890aa8dd5c4f4c36cfd2e36b5718bd3662b976838997375cc158"

      define_method(:install) do
        bin.install "fbcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/facebook-cli/releases/download/v0.1.0/facebook-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "76bb68509c32584379f0ab5e7fe50411c8a2363475c707e67f8892a979efabd3"

      define_method(:install) do
        bin.install "fbcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/facebook-cli/releases/download/v0.1.0/facebook-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "8b4b991f2adc76f2af09cc6b460f96c2e7ac9a6f2ff7a29a3543def3e70e2c26"
      define_method(:install) do
        bin.install "fbcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/facebook-cli/releases/download/v0.1.0/facebook-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "58bb2d7a63f9bcba231f2632c3f68f862e9d93c732bd1d0c7f0a94e55702bc69"
      define_method(:install) do
        bin.install "fbcli"
      end
    end
  end

  test do
    system "#{bin}/fbcli", "--help"
  end
end
