# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FacebookCli < Formula
  desc "CLI for Facebook Graph API to manage pages, posts, ads, and analytics"
  homepage "https://github.com/salmonumbrella/facebook-cli"
  version "3.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/facebook-cli/releases/download/v3.0.1/facebook-cli_3.0.1_darwin_amd64.tar.gz"
      sha256 "d6e2ff7af602248f2fd0c9ffb5ec6686b1f1aa97856aeb2423e4b538ac49c9b4"

      define_method(:install) do
        bin.install "fbcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/facebook-cli/releases/download/v3.0.1/facebook-cli_3.0.1_darwin_arm64.tar.gz"
      sha256 "6a508dcfc2f5103b7f54d5d8569deba3b2bc9c99a2e5a40c618f963b04e32e77"

      define_method(:install) do
        bin.install "fbcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/facebook-cli/releases/download/v3.0.1/facebook-cli_3.0.1_linux_amd64.tar.gz"
      sha256 "0f31dc308d23ef70f8c5705cc4c511cf4216bafa2585e2e2f9c05130afb25bd6"
      define_method(:install) do
        bin.install "fbcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/facebook-cli/releases/download/v3.0.1/facebook-cli_3.0.1_linux_arm64.tar.gz"
      sha256 "78b3715b1bf5d8c9d26d362f5dc151603fd829c43233a6a2f5f5bdfadb28c5cc"
      define_method(:install) do
        bin.install "fbcli"
      end
    end
  end

  test do
    system "#{bin}/fbcli", "--help"
  end
end
