# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FastmailCli < Formula
  desc "CLI for Fastmail to manage emails, folders, and masked addresses"
  homepage "https://github.com/salmonumbrella/fastmail-cli"
  version "0.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/fastmail-cli/releases/download/v0.2.8/fastmail_0.2.8_darwin_amd64.tar.gz"
      sha256 "2a0d77613caedca4d283bd8b77bc0efceb7870d3b43573f4fda728fa739d2fb4"

      def install
        bin.install "fastmail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/fastmail-cli/releases/download/v0.2.8/fastmail_0.2.8_darwin_arm64.tar.gz"
      sha256 "6b27bbcf332f6a195c71491942bc30d5ac87278c5c81d6160ef16273f87faf4a"

      def install
        bin.install "fastmail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/fastmail-cli/releases/download/v0.2.8/fastmail_0.2.8_linux_amd64.tar.gz"
      sha256 "fdfb0efa4aad3b36c1db3042a5925d919b47d9c5659750a19cb202bc2bdb77de"
      def install
        bin.install "fastmail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/fastmail-cli/releases/download/v0.2.8/fastmail_0.2.8_linux_arm64.tar.gz"
      sha256 "33a2d74ef53620ba164aa1e43dd20c8616a5ccf6c885136e5f63ecf9874b366e"
      def install
        bin.install "fastmail"
      end
    end
  end

  test do
    system "#{bin}/fastmail", "--help"
  end
end
