# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstantlyCli < Formula
  desc "Agent-friendly CLI for Instantly.ai"
  homepage "https://github.com/salmonumbrella/instantly-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/instantly-cli/releases/download/v0.1.1/instantly-cli_darwin_amd64.tar.gz"
      sha256 "f99615074dd0bd1c95dd24f7efb928efdd5bc8a62b725aa47a2f0bf4718ea1a1"

      define_method(:install) do
        bin.install "instantly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/instantly-cli/releases/download/v0.1.1/instantly-cli_darwin_arm64.tar.gz"
      sha256 "490f82d72bd671bbeea0d0a10885dfffee4cabb5b1801b7afb614e8fd7a80ea7"

      define_method(:install) do
        bin.install "instantly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/instantly-cli/releases/download/v0.1.1/instantly-cli_linux_amd64.tar.gz"
      sha256 "5c180c3deb293c639daf57edd9d227b2b9e1f35ac12b6fde1cd8d53531baf19a"
      define_method(:install) do
        bin.install "instantly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/instantly-cli/releases/download/v0.1.1/instantly-cli_linux_arm64.tar.gz"
      sha256 "9e86e93ede7fd82ed5c3463fd93eb488b886ea8141893460b10ec1f5818f3c2f"
      define_method(:install) do
        bin.install "instantly"
      end
    end
  end

  test do
    system "#{bin}/instantly", "--help"
  end
end
