# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstantlyCli < Formula
  desc "Agent-friendly CLI for Instantly.ai"
  homepage "https://github.com/salmonumbrella/instantly-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/instantly-cli/releases/download/v0.1.0/instantly-cli_darwin_amd64.tar.gz"
      sha256 "4c456e85b27714642aa06076039e99a463561f2a89bb9b402f2155e26e3e672c"

      def install
        bin.install "instantly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/instantly-cli/releases/download/v0.1.0/instantly-cli_darwin_arm64.tar.gz"
      sha256 "72718b4209767140ac2b502e28e592f4d76c8fbe1e8b96877f2f0c5de0840ad0"

      def install
        bin.install "instantly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/instantly-cli/releases/download/v0.1.0/instantly-cli_linux_amd64.tar.gz"
      sha256 "eb965a7ff56ba96755111a95a90eafa553c7d616caf5512d35a7c39a131dddf0"
      def install
        bin.install "instantly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/instantly-cli/releases/download/v0.1.0/instantly-cli_linux_arm64.tar.gz"
      sha256 "4552f334ce9fe45aa0ca53373028384c66f69920d18b01f71280bbb485cbca20"
      def install
        bin.install "instantly"
      end
    end
  end

  test do
    system "#{bin}/instantly", "--help"
  end
end
