# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LineCli < Formula
  desc "CLI for LINE Official Account / Messaging API"
  homepage "https://github.com/salmonumbrella/line-official-cli"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v0.3.4/line-cli_0.3.4_darwin_amd64.tar.gz"
      sha256 "7374264fe7e551ae33a5891157e1b1fea7bbe1dea5ccca39967a1cc541f1ac48"

      def install
        bin.install "line"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v0.3.4/line-cli_0.3.4_darwin_arm64.tar.gz"
      sha256 "6b9f132a0e1dff232c187f241e6ee01d6f54ef52419be5ffb200ec623c69506c"

      def install
        bin.install "line"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v0.3.4/line-cli_0.3.4_linux_amd64.tar.gz"
      sha256 "d8f7b5e65d8d4a6a5f066e1b7e1becdb7798e192f5aa5f6b7866b4c6737b8498"
      def install
        bin.install "line"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v0.3.4/line-cli_0.3.4_linux_arm64.tar.gz"
      sha256 "ec3a0bc5cf676dd379762fa84788973097b18bc786fa6f36a3ff54d7a3107419"
      def install
        bin.install "line"
      end
    end
  end

  test do
    system "#{bin}/line", "--help"
  end
end
