# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LineCli < Formula
  desc "CLI for LINE Official Account / Messaging API"
  homepage "https://github.com/salmonumbrella/line-official-cli"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v0.3.3/line-cli_0.3.3_darwin_amd64.tar.gz"
      sha256 "a113262690eade985f5d61de11557018e20de62c8ee32aa2748c784402f2433e"

      def install
        bin.install "line"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v0.3.3/line-cli_0.3.3_darwin_arm64.tar.gz"
      sha256 "47bc88f80f122fc28ddb61921d3712841baf6e263f97175b971e8596ebef6d51"

      def install
        bin.install "line"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v0.3.3/line-cli_0.3.3_linux_amd64.tar.gz"
      sha256 "7b26dc625bd53e471cd68cdf63146032432c4899a1df48205e5b5450b8d04dce"
      def install
        bin.install "line"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/line-official-cli/releases/download/v0.3.3/line-cli_0.3.3_linux_arm64.tar.gz"
      sha256 "067fa6e5c2a572e5a8f310fe5f99d81f95aa8e1ed8a87c046288b237996ba3e8"
      def install
        bin.install "line"
      end
    end
  end

  test do
    system "#{bin}/line", "--help"
  end
end
