# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionCli < Formula
  desc "CLI for Notion API"
  homepage "https://github.com/salmonumbrella/notion-cli"
  version "0.5.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v0.5.15/notion_0.5.15_darwin_amd64.tar.gz"
      sha256 "9d2f0d050b4d9a935a5c779ecb9217d005f547c0dc5687c056349afe6b5bc1a6"

      def install
        bin.install "ntn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v0.5.15/notion_0.5.15_darwin_arm64.tar.gz"
      sha256 "9f441295d48f6b2400c1eea2e9f165af4176e231cde9d1ab5192073b856ddc2a"

      def install
        bin.install "ntn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v0.5.15/notion_0.5.15_linux_amd64.tar.gz"
      sha256 "e18dec706a6e0e5d5a4a52544ad6722620b7554d47beae5526ad88bde1aa1178"
      def install
        bin.install "ntn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v0.5.15/notion_0.5.15_linux_arm64.tar.gz"
      sha256 "2968f496da678a183e6efc25527a5b0c9d787bc79fc00f5303fbc586d2a0ddda"
      def install
        bin.install "ntn"
      end
    end
  end

  test do
    system "#{bin}/ntn", "--help"
  end
end
