# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionCli < Formula
  desc "CLI for Notion API"
  homepage "https://github.com/salmonumbrella/notion-cli"
  version "0.5.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v0.5.16/notion_0.5.16_darwin_amd64.tar.gz"
      sha256 "ceb7f34021cb3de902f365d2efdef03511034b2a957f7d9acbd1782693a153e2"

      def install
        bin.install "ntn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v0.5.16/notion_0.5.16_darwin_arm64.tar.gz"
      sha256 "bcdb07edfce00c06367eea7679b30c7aaf03f9a9afe8bcde1224ac3fd815712c"

      def install
        bin.install "ntn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v0.5.16/notion_0.5.16_linux_amd64.tar.gz"
      sha256 "f378f9c56333425dd646b869e4115f00b6e36f3ed3f0034e1365802b2e803f7c"
      def install
        bin.install "ntn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/notion-cli/releases/download/v0.5.16/notion_0.5.16_linux_arm64.tar.gz"
      sha256 "62b9c5665cca7ca1ad73bc400ffab99cc2b15a5f8a127341649ddee0dcbe60ac"
      def install
        bin.install "ntn"
      end
    end
  end

  test do
    system "#{bin}/ntn", "--help"
  end
end
