# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotteCli < Formula
  desc "CLI for Notte to automate browsers, extract data, and run tasks"
  homepage "https://github.com/salmonumbrella/notte-cli"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/notte-cli/releases/download/v0.1.7/notte-cli_0.1.7_darwin_amd64.tar.gz"
      sha256 "7f6c62e35c71378792e03dad7c5cdc0ab4616d8d4b1452613953d09eb7c0657f"

      define_method(:install) do
        bin.install "notte"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/notte-cli/releases/download/v0.1.7/notte-cli_0.1.7_darwin_arm64.tar.gz"
      sha256 "d45df5baa5d7967d37478675c97e9df7c19b2f4b51dc49d266c153ceb542462d"

      define_method(:install) do
        bin.install "notte"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/notte-cli/releases/download/v0.1.7/notte-cli_0.1.7_linux_amd64.tar.gz"
      sha256 "b5d7027c2a693cd5d4625a8de8dcb1e2825643999668f60fefc37c2f6038c3be"
      define_method(:install) do
        bin.install "notte"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/notte-cli/releases/download/v0.1.7/notte-cli_0.1.7_linux_arm64.tar.gz"
      sha256 "a4431c415313998a6ea8fbe12d6e1d5133e3cec9837f5ac28b0aa248bf3a83d3"
      define_method(:install) do
        bin.install "notte"
      end
    end
  end

  test do
    system "#{bin}/notte", "--help"
  end
end
