# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShoplineCli < Formula
  desc "CLI for Shopline e-commerce platform"
  homepage "https://github.com/salmonumbrella/shopline-cli"
  version "0.7.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/shopline-cli/releases/download/v0.7.15/shopline-cli_darwin_amd64.tar.gz"
      sha256 "23b38764dad2f10a2bfef52dbf453891bd3a43f64a715e4d42bb18675c0ec356"

      define_method(:install) do
        bin.install "spl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/shopline-cli/releases/download/v0.7.15/shopline-cli_darwin_arm64.tar.gz"
      sha256 "78f85e2c5cc96dda20e997997e39c6cc568bd42ed4a9610c7086b65fb59bc5bf"

      define_method(:install) do
        bin.install "spl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/shopline-cli/releases/download/v0.7.15/shopline-cli_linux_amd64.tar.gz"
      sha256 "3ebe4cae0e407ea780360e67c28d2d8aac9dd0b0d5342ad98850d9ac078de66d"
      define_method(:install) do
        bin.install "spl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/shopline-cli/releases/download/v0.7.15/shopline-cli_linux_arm64.tar.gz"
      sha256 "ed1b9ec5d8ef025a9b9bec4c444b63e0a8766b2d2e3bc8a1fc11bc4a7797c93f"
      define_method(:install) do
        bin.install "spl"
      end
    end
  end

  test do
    system "#{bin}/spl", "--help"
  end
end
