# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShoplineCli < Formula
  desc "CLI for Shopline e-commerce platform"
  homepage "https://github.com/salmonumbrella/shopline-cli"
  version "0.7.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/shopline-cli/releases/download/v0.7.10/shopline-cli_darwin_amd64.tar.gz"
      sha256 "b646c2bbf69cceaaa6804bebbff7ff3f0f93ae4e5c856bfd5fe20397b72ca162"

      def install
        bin.install "spl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/shopline-cli/releases/download/v0.7.10/shopline-cli_darwin_arm64.tar.gz"
      sha256 "0e3b76ab0e212aef782b9067ecacff09dfe8cc80f52814c7aacd33d4985ec98e"

      def install
        bin.install "spl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/shopline-cli/releases/download/v0.7.10/shopline-cli_linux_amd64.tar.gz"
      sha256 "547f3a4ef4abe6c26bf24e893df26c806bc77873c541bbe9f28ca0f9ac2a5d0a"
      def install
        bin.install "spl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/shopline-cli/releases/download/v0.7.10/shopline-cli_linux_arm64.tar.gz"
      sha256 "7668e7ae8db87edcced4d486924a253e29e9913578b17d1294822368f577afa3"
      def install
        bin.install "spl"
      end
    end
  end

  test do
    system "#{bin}/spl", "--help"
  end
end
