# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShoplineCli < Formula
  desc "CLI for Shopline e-commerce platform"
  homepage "https://github.com/salmonumbrella/shopline-cli"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/shopline-cli/releases/download/v0.7.2/shopline-cli_darwin_amd64.tar.gz"
      sha256 "79077be2c86b52cb3ca6bf3975bb8cbfa71be580ef21bfa2ef57eb1b1ff7cdd4"

      def install
        bin.install "spl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/shopline-cli/releases/download/v0.7.2/shopline-cli_darwin_arm64.tar.gz"
      sha256 "3f96fff8ef065b0bfb35e3154dc49e16a7c8b6f0d15b69aae43cda0deae64da8"

      def install
        bin.install "spl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/shopline-cli/releases/download/v0.7.2/shopline-cli_linux_amd64.tar.gz"
      sha256 "7313e20cd4a1af133f63369c5f24ab2ad87d41c0a8097ac40febf1792ad70f5d"
      def install
        bin.install "spl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/shopline-cli/releases/download/v0.7.2/shopline-cli_linux_arm64.tar.gz"
      sha256 "c52651fafe004fcdf7f15f1c821785cea9d36698160b7b88bdfc51ef042dadb5"
      def install
        bin.install "spl"
      end
    end
  end

  test do
    system "#{bin}/spl", "--help"
  end
end
