# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ThreadsCli < Formula
  desc "CLI for Threads API by Meta - manage posts, replies, insights"
  homepage "https://github.com/salmonumbrella/threads-cli"
  version "1.4.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/threads-cli/releases/download/v1.4.7/threads_1.4.7_darwin_amd64.tar.gz"
      sha256 "4ed72d063a47bee95d3173603f284b3ed154a41be6cd2b13d07ac22fc9089498"

      define_method(:install) do
        bin.install "threads"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/threads-cli/releases/download/v1.4.7/threads_1.4.7_darwin_arm64.tar.gz"
      sha256 "b6abd7934d73afe9dabe1ffc02c86d14d4893a81e9414f003ae862c3f5e8bf9f"

      define_method(:install) do
        bin.install "threads"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/threads-cli/releases/download/v1.4.7/threads_1.4.7_linux_amd64.tar.gz"
      sha256 "95f5c96e01684fffe366d8b2ba630617347364042c5dd9ee72138613ad1ef2e0"
      define_method(:install) do
        bin.install "threads"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/threads-cli/releases/download/v1.4.7/threads_1.4.7_linux_arm64.tar.gz"
      sha256 "b08f420ed80d136337d3ed30710c812a8b6b8125f8b87114744ccbafc0f994f4"
      define_method(:install) do
        bin.install "threads"
      end
    end
  end

  test do
    system "#{bin}/threads", "--help"
  end
end
