# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TwentyCli < Formula
  desc "CLI for Twenty CRM with 100% API coverage"
  homepage "https://github.com/salmonumbrella/twenty-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/salmonumbrella/twenty-cli/releases/download/v0.1.0/twenty_0.1.0_darwin_amd64.tar.gz"
      sha256 "13170ce279848e0db1e0a76cd537400027c77588cb20464571e510403b2db941"

      def install
        bin.install "twenty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/salmonumbrella/twenty-cli/releases/download/v0.1.0/twenty_0.1.0_darwin_arm64.tar.gz"
      sha256 "8121ab3a638fa77e5d6d5e784c868001ad1734e727536d7a47d458d9c55426e4"

      def install
        bin.install "twenty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/twenty-cli/releases/download/v0.1.0/twenty_0.1.0_linux_amd64.tar.gz"
      sha256 "1129ae47a5b7308e6dc901a905924bd38858a736855107dd13efc517546f7092"
      def install
        bin.install "twenty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salmonumbrella/twenty-cli/releases/download/v0.1.0/twenty_0.1.0_linux_arm64.tar.gz"
      sha256 "9c9ea1bf639b03d322875463c95cf8691f4f69234a93c458f953cf05d6646f83"
      def install
        bin.install "twenty"
      end
    end
  end

  test do
    system "#{bin}/twenty", "--version"
  end
end
